version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "gsheets-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bds9zolxdlbk"
s3_prefix = "gsheets-api"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
# parameter_overrides = "GooglePrivateKey=\"{{resolve:ssm:GoogleSheetPrivateKey:1}}\" GoogleClientEmail=\"{{resolve:ssm:GoogleSheetClientEmail:1}}\" GoogleSpreadsheetId=\"1h_cKOqg5UIPg-Mfrqj4P0mzcnejTQIgkOJVvil-apgg\" GoogleUsersSheetName=\"Lambda\""
image_repositories = []
